defaults: &defaults
  hoge_number:
    min: 1
    max: 99
  attendance_status: ['未回答', '出席', '遅刻', '当日決定', '未定', '5', '6', '7', '8', '欠席']
  test_stat : ['1', '2', '3']

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
