defaults: &defaults
  hoge_number:
    min: 1
    max: 99
  attendance_status: ['未回答', '出席', '遅刻参加', '当日決定', '未定', '5', '6', '7', '8', '欠席']
  member_status: ['テスト会員', '正会員', '準会員', '休部', '退会']

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
